---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - epinio.apps.epinio.io
  resources:
  - installepinios
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - epinio.apps.epinio.io
  resources:
  - installepinios/finalizers
  verbs:
  - update
- apiGroups:
  - epinio.apps.epinio.io
  resources:
  - installepinios/status
  verbs:
  - get
  - patch
  - update
