apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ui
  namespace: {{ .Values.namespace }}
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: epinio
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: ui
  selector:
    control-plane: controller-manager
    app.kubernetes.io/name: epinio
